# Generated by Django 4.0 on 2022-01-04 15:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenitie',
            fields=[
                ('amenty_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_stay', models.IntegerField()),
                ('max_stay', models.IntegerField()),
                ('floor_no', models.IntegerField()),
                ('is_furnished', models.BooleanField()),
                ('has_kitchen', models.BooleanField()),
                ('has_internet', models.BooleanField()),
                ('has_parking', models.BooleanField()),
                ('has_garden', models.BooleanField()),
                ('has_terrace', models.BooleanField()),
                ('total_bedrooms', models.IntegerField()),
                ('available_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_attach_bathrooms', models.BooleanField()),
                ('total_rooms_in_house', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('pets_allowed', models.BooleanField()),
                ('deposit', models.BooleanField()),
                ('smoking_allowed', models.BooleanField()),
                ('couples_allowed', models.BooleanField()),
                ('single_occupancy', models.BooleanField()),
                ('preferred_gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('B', 'BOTH')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=5)),
                ('state', models.CharField(choices=[('1', 'STATE 1'), ('2', 'STATE 2'), ('3', 'STATE 3'), ('4', 'STATE 4'), ('5', 'STATE 5'), ('6', 'STATE 6'), ('7', 'STATE 7')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(choices=[('R', 'ROOM'), ('F', 'FLAT'), ('A', 'APPARTMENT'), ('H', 'HOUSE')], max_length=1)),
                ('images', models.URLField()),
                ('photo', models.ImageField(upload_to='rooms')),
                ('no_of_room_to_rent', models.IntegerField()),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.amenitie')),
                ('house_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.houserule')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=50)),
                ('mime_type', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
