# Generated by Django 3.2.3 on 2021-05-24 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('amenty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_furnished', models.BooleanField()),
                ('has_parking', models.BooleanField()),
                ('has_garden', models.BooleanField()),
                ('has_terrace', models.BooleanField()),
                ('has_attach_bathrooms', models.BooleanField()),
                ('floor_no', models.BooleanField()),
                ('total_rooms_in_house', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseRules',
            fields=[
                ('rule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('smoking_allowed', models.BooleanField()),
                ('pets_allowed', models.BooleanField()),
                ('couples_allowed', models.BooleanField()),
                ('preferred_gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('B', 'BOTH')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=5)),
                ('state', models.CharField(choices=[('1', 'STATE 1'), ('2', 'STATE 2'), ('3', 'STATE 3'), ('4', 'STATE 4'), ('5', 'STATE 5'), ('6', 'STATE 6'), ('7', 'STATE 7')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('property_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_type', models.CharField(choices=[('R', 'ROOM'), ('F', 'FLAT'), ('A', 'APPARTMENT'), ('H', 'HOUSE')], max_length=1)),
                ('images', models.URLField()),
                ('no_of_room_to_rent', models.IntegerField()),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.amenities')),
                ('house_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.houserules')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
        migrations.DeleteModel(
            name='personal_rooms',
        ),
    ]
