# Generated by Django 3.2.3 on 2021-05-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_amenitie_floor_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenitie',
            name='amenty_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='houserule',
            name='rule_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='property_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
